### ISSUE TITLE
Request for Feature to Customize Character Appearance

### ISSUE THREAD

**Issue by still1987** [arenasys/palworld-appearance-transfer#1]
Dear Developer,

First of all, I would like to express my deepest gratitude for your contribution. Your design is truly ingenious, a work of genius!

While using your software, I thought that the ability to customize the character's appearance would greatly enhance the user experience. Specifically, the option to change a character's gender would be a tremendously useful feature. I understand this might be a complex feature to implement, so even starting with basic body type changes, such as between Body Type 1 and Body Type 2, would be fantastic.

Do you have plans to incorporate such a feature in future updates? If community support is needed, myself and other users are willing to help out.

Thank you once again for your hard work and contribution!

Best regards,

**Comment by arenasys** [comment]
Cant just create a new character the way you want then transfer its appearance
